export enum constants {
    GET_TODOS_REQUEST = "GET_TODOS_REQUEST",
    GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS",
    GET_TODOS_FAILURE = "GET_TODOS_FAILURE",
    CREATE_TO_DO = "CREATE_TO_DO_REQUEST",
    CREATE_TODO_SUCCESS= "CREATE_TODO_SUCCESS",
    CREATE_TODO_FAILURE= "CREATE_TODO_FAILURE",
    REMOVE_TODO = "REMOVE_TODO",
    REMOVE_TODO_SUCCESS= "REMOVE_TODO_SUCCESS",
    REMOVE_TODO_FAILURE= "REMOVE_TODO_FAILURE",
    EDIT_TODO = "EDIT_TODO",
    EDIT_TODO_SUCCESS= "EDIT_TODO_SUCCESS",
    EDIT_TODO_FAILURE= "EDIT_TODO_FAILURE",
    CLEAR_ALL_TASKS = "CLEAR_ALL_TASKS"
  }
  